### PR TITLE
fix: Use our data set to work out if a module is a node module

### LINKED ISSUE #337: Bug: prefer-node-protocol rule and deprecated builtins
### Environment

Node version: 22.7.0
npm version: 10.8.2
ESLint version: 8.57.0
eslint-plugin-n version: 17.10.2
Operating System: Linux

### What rule do you want to report?

prefer-node-protocol

### Link to Minimal Reproducible Example

https://eslint-online-playground.netlify.app/#eNptkMFugzAMhl8l8qUXoFuPVNtpb7H0gIJB2YITOaFqhXj3OQ1om9SLY1uf//z2ApHNEW/dFBw2XxFasFPwnFSY6W58j2pgP6nDXh7OUAFGZyk1xtNgx39TVHC9IXVw82ipJg1nTZrw9qB6HLrZJfWpSaklB6UKGVu1iMhalSbPDnOrVEp06RgYB+SaxEwd2CdvvNPQihggs2cN1e9AHrkiR+vFQivF+9vp1Lw2L0LtzHop2ZofCRexKkuGznx3Yz6KJ1nwIakh3QMWpcn34m7T0dDj9QMDUo9kLMbMbC72Y5Qx1yWMkm/fP7nUX2qztML6A41SiaQ=

### What did you expect to happen?

The `prefer-node-protocol` is reporting the import of `punycode`, as missing the `node:` prefix, which is intended. The issue is the `punycode` Node builtin is deprecated and we are encouraged to use a third party module instead.
Which we do in our codebase currently. We use a module called [`punycode`](https://www.npmjs.com/package/punycode), so we don't want to prefix it obviously.

See https://nodejs.org/api/punycode.html#punycode

So it would be a good thing to maybe have another option to the rule to be able to ignore certain Node builtins?

```js
"n/prefer-node-protocol": ["error", {
  "ignore": ['punycode'],
}]
```

Alternatively the plugin could maintain a list of deprecated builtins related to the Node version and exclude them, but that sound quite tedious and not optimal. Also not working with ESM.   

We should note that we can work around this issue with `import punycode from 'punycode/'` but is that's not realy satisfactory.

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by scagood**
closes #337

### CODE REVIEW

File: lib/rules/prefer-node-protocol.js [hunk 1]
```diff
@@ -4,12 +4,22 @@
...
 
-const { isBuiltin } = require("node:module")
 const getConfiguredNodeVersion = require("../util/get-configured-node-version")
 const getSemverRange = require("../util/get-semver-range")
 const visitImport = require("../util/visit-import")
 const visitRequire = require("../util/visit-require")
 const mergeVisitorsInPlace = require("../util/merge-visitors-in-place")
+const {
+    NodeBuiltinModules,
+} = require("../unsupported-features/node-builtins.js")
```
Comment (aladdin-add) [inline lib/rules/prefer-node-protocol.js:14]: nits: we could move `node-builtins.js` to outer - it's now not just used by those rules. :)

**Review by aladdin-add — APPROVED** [review]

File: lib/rules/prefer-node-protocol.js (hunk 1 above)
Comment (scagood) [reply lib/rules/prefer-node-protocol.js:14]: Where do you think we should put the directory?

I was also thinking about going through and merging the [`no-deprecated-api`](https://github.com/eslint-community/eslint-plugin-n/blob/master/lib/rules/no-deprecated-api.js#L27) into the `[`unsupported-features`](https://github.com/eslint-community/eslint-plugin-n/tree/master/lib/unsupported-features)` so its all in one place as a consistent data set 🤔

Comment (aladdin-add) [reply lib/rules/prefer-node-protocol.js:14]: > Where do you think we should put the directory?

maybe `/lib/dataset/`?

> I was also thinking about going through and merging the [no-deprecated-api](https://github.com/eslint-community/eslint-plugin-n/blob/master/lib/rules/no-deprecated-api.js#L27) into the [unsupported-features](https://github.com/eslint-community/eslint-plugin-n/tree/master/lib/unsupported-features)

It would be nice if these rules could share data, so we don't have to worry about updating one and forgetting the other.
