### PR TITLE
fix: no-callback-literal ignore unknown nodes

### LINKED ISSUE #162: Bug: `no-callback-literal`
### Environment

Node version: v20.10.0
npm version: 10.2.3
ESLint version: v8.56.0
eslint-plugin-n version: 16.6.1
Operating System: macOS 14

### What rule do you want to report?

no-callback-literal

### Link to Minimal Reproducible Example

N/A

### What did you expect to happen?

```ts
let result: string

try {
  result = renderToString(component)

  if (options.template) {
    result = templateRenderer.renderSync(result, context)
  }
  cb(null, result)
} catch (err) {
  cb(err as Error) // `Unexpected literal in error position of callback.` error here
}
```

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by aladdin-add**
fixes #162

### CODE REVIEW

**Review by scagood — APPROVED** [review]

File: lib/rules/no-callback-literal.js [hunk 1]
```diff
@@ -62,7 +62,8 @@ function couldBeError(node) {
         case "TaggedTemplateExpression":
         case "YieldExpression":
             return true // possibly an error object.
-
+        case "Literal":
+            return node.value == null
```
Comment (aladdin-add) [inline lib/rules/no-callback-literal.js:66]: according its docs, the arg can be null/undefined, so I changed `===` to `==`, to allow cases like `cb(undefined)`

**Comment by scagood** [comment]
We should probably also merge this into 16.x and release it 🤔
